### PR TITLE
Update version of lalrpop

### PR DESCRIPTION
**Pull request by TomLisankie**
Updated version of lalrpop since it was crashing during compilation with new Rust versions.

### CODE REVIEW

**Comment by BatmanAoD** [comment]
Does it build? I tried to do this update a while ago and couldn't get it to work.

**Comment by BatmanAoD** [comment]
Summary of my progress: https://github.com/willcrichton/lia/issues/2#issuecomment-483873564

**Comment by TomLisankie** [comment]
@BatmanAoD No, but it gets much further in the compile processes. Then it crashes when it's trying to read the `grammar.lalrpop` file.

**Comment by BatmanAoD** [comment]
Try using my fork as a base.

**Pull request closed without merging**
